server:
  url: ${server.domain}:${server.port}

spring:
  application:
    name: company-service
  profiles:
    active: local

# Eureka Client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/