server:
  url: ${server.domain}:${server.port}

spring:
  application:
    name: user-service
  profiles:
    active: local

  # Flyway
  flyway:
    enabled: false
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration

# Eureka Client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

###
yandex:
  api:
   key: fcc4869a-2b63-48f4-960f-f3fd2b6747ae